#!/bin/sh

# build from source
#sudo apt install -y ninja-build gettext libtool libtool-bin cmake pkg-config doxygen
#git clone https://github.com/neovim/neovim.git ~/.config/neovim && cd ~/.config/neovim
#make -j4 && sudo make install

# Debian
# sudo apt install -y nodejs npm ruby ueberzug ccls && cargo install ttyper bat procs
# shfmt shellcheck stylua
# curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz" && sudo tar xf lazygit.tar.gz -C /usr/local/bin lazygit

# Void
# sudo xbps-install -Sy nodejs ruby ueberzug lazygit ccls && cargo install ttyper
# shfmt shellcheck stylua

# Arch
sudo pacman -S --noconfirm nodejs npm ruby ueberzug lazygit ccls
# shfmt shellcheck stylua

# npm dependences
sudo npm i -g google-java-format live-server emmet
# luacheck eslint eslint_d html tailwindcss prettier astyle

# pip dependences
pip install pynvim
# sourcery

# go-dap
go install github.com/go-delve/delve/cmd/dlv@latest

# setup rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
rustup component add rust-analyzer
# cargo new project  # get started with rust

# creating python venv for dap
# mkdir ~/.virtualenvs
# cd ~/.virtualenvs || exit
# python -m venv debugpy
# debugpy/bin/python -m pip install debugpy

# javascript-dap
# mkdir -p ~/dev/microsoft
# git clone https://github.com/microsoft/vscode-node-debug2.git ~/dev/microsoft/vscode-node-debug2
# cd ~/dev/microsoft/vscode-node-debug2 || exit
# npm install
# NODE_OPTIONS=--no-experimental-fetch npm run build
