#!/bin/sh

# build from source
#sudo apt install -y ninja-build gettext libtool libtool-bin cmake pkg-config doxygen
#git clone https://github.com/neovim/neovim.git ~/.config/neovim && cd ~/.config/neovim
#make -j4 && sudo make install

# packer install
git clone --depth 1 https://github.com/wbthomason/packer.nvim \
	~/.local/share/nvim/site/pack/packer/start/packer.nvim

# Debian
# sudo apt install -y nodejs npm ccls shfmt shellcheck ueberzug && cargo install stylua ttyper bat procs
# curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz" && sudo tar xf lazygit.tar.gz -C /usr/local/bin lazygit

# Arch
# sudo pacman -S --noconfirm nodejs npm ccls shfmt shellcheck ueberzug stylua lazygit

# Void
# sudo xbps-install -Sy nodejs ccls shfmt shellcheck ueberzug lazygit && cargo install stylua ttyper

# npm dependences
sudo npm i -g prettier astyle luacheck emmet eslint eslint_d html tailwindcss live-server

# pip dependences
pip install pynvim black flake8 sourcery
