#!/bin/sh

distro=$(grep ID= /etc/os-release | sed -n 2p | cut -d= -f2)

if [ "$distro" = "debian" ] || [ "$distro" = "ubuntu" ] || [ "$distro" = "kali" ]; then
	printf "Build neovim? (y/N): "
	read -r choice
	if [ "$choice" = "y" ]; then
		sudo apt install -y ninja-build gettext
		git clone https://github.com/neovim/neovim.git ~/.cache/neovim
		cd ~/.cache/neovim || exit 1
		make -j4 && sudo make install
	else
		:
	fi

	## dependences
	sudo apt install -y npm cargo luarocks \
		golang php ruby \
		ripgrep \
		python3-pip python3-venv \
		default-jdk dotnet-sdk-6.0
	# wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
	# chmod +x ./dotnet-install.sh && ./dotnet-install.sh --version latest

	printf "Install cargo pkgs? (y/N): "
	read -r choice
	if [ "$choice" = "y" ]; then
		cargo install procs bat
	else
		:
	fi

	# wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb && sudo dpkg -i cloudflared-linux-amd64.deb
	# curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz" && sudo tar xf lazygit.tar.gz -C /usr/local/bin lazygit

	# julia
	## curl -s https://api.github.com/repos/JuliaLang/julia/releases | grep -oP '"tag_name": "\K(.*?)(?=")' # check version
	printf "Want to install julia? (y/N): "
	read -r choice
	if [ "$choice" = "y" ]; then
		wget https://julialang-s3.julialang.org/bin/linux/x64/1.8/julia-1.8.5-linux-x86_64.tar.gz
		tar -xvzf julia-1.8.5-linux-x86_64.tar.gz
		sudo mv julai-1.8.5 /opt/
		sudo ln -s /opt/julia-1.8.5/bin/julia /usr/local/bin/julia
	else
		:
	fi
else
	:
fi

distro=$(lsb_release -a | grep 'Distributor ID' | cut -f 2)
if [ "$distro" = "Artix" ]; then
	sudo pacman -S --noconfirm npm cargo luarocks \
		go php ruby \
		ripgrep \
		jdk-openjdk dotnet-sdk \
		cloudflared lazygit julia
else
	:
fi

## node dependences
sudo npm i -g tree-sitter-cli live-server

## python dependences
pip install pynvim

## rust setup
printf "Install rustfmt ? (y/n): "
read -r choice
if [ "$choice" = "y" ]; then
	rustup component add rustfmt
else
	:
fi

## kotlin setup
# curl -s "https://get.sdkman.io" | bash
# sdk install kotlin
