require("user.settings")
require("user.keymaps")
require("user.plugins")
require("user.gitsigns")
require("user.toggleterm")
require("user.colorizer")
require("user.scheme")
require("user.zen-mode")
require("user.impatient")
require("user.indentline")
require("user.mason")
require("user.lualine")
require("user.icons")
require("user.nvim-tree")
require("user.bufferline")
require("user.surround")
vim.notify = require("notify")
require("user.telescope")
require("user.project")
require("user.alpha")
require("user.treesitter")
require("user.comment")
require("user.autopairs")
require("user.illuminate")
require("user.autocmd")
require("user.saga")
require("user.cmp")

-- Dynamic
require("user.whichkey")
require("user.lsp")
require("user.ufo")
require("user.dap")
