return {
  "utilyre/barbecue.nvim",
  name = "barbecue",
  version = "*",
  event = "BufReadPost",
  dependencies = {
    "SmiteshP/nvim-navic",
  },
  opts = {
    exclude_filetypes = { "netrw", "toggleterm" },
    show_basename = false,
    symbols = {
      separator = "›",
    },
    kinds = {
      File = "",
      Module = "",
      Namespace = "󰦮",
      Package = "",
      Class = "",
      Method = "",
      Property = "󰓹",
      Field = "",
      Constructor = "",
      Enum = "",
      Interface = "",
      Function = "ƒ",
      Variable = "",
      Constant = "П",
      String = "",
      Number = "󰎠",
      Boolean = "",
      Array = "",
      Object = "",
      Key = "",
      Null = "",
      EnumMember = "",
      Struct = "",
      Event = "",
      Operator = "±",
      TypeParameter = "",
    },
  },
}
