return {
	"saghen/blink.cmp",
	version = "1.*",
	dependencies = { "rafamadriz/friendly-snippets" },
	event = "InsertEnter",
	opts = {
		keymap = {
			preset = "enter",
			["<C-y>"] = { "select_and_accept" },
		},
		appearance = {
			kind_icons = {
				Text = "",
				Method = "",
				Function = "ƒ",
				Constructor = "",
				Field = "",
				Variable = "",
				Property = "󰓹",
				Class = "",
				Interface = "",
				Struct = "",
				Module = "󰩦",
				Unit = "",
				Value = "",
				Enum = "",
				EnumMember = "",
				Keyword = "",
				Constant = "П",
				Snippet = "",
				Color = "",
				File = "",
				Reference = "",
				Folder = "",
				Event = "",
				Operator = "",
				TypeParameter = "",
			},
		},
		completion = {
			menu = { draw = { treesitter = { "lsp" } } },
			documentation = { auto_show = true, auto_show_delay_ms = 300 },
		},
		sources = { default = { "lsp", "path", "snippets", "buffer" } },
	},
	opts_extend = { "sources.default" },
}
