return {
	-- "kristijanhusak/vim-dadbod-ui",
	-- cmd = { "DBUI", "DBUIToggle", "DBUIAddConnection", "DBUIFindBuffer" },
	-- dependencies = {
	-- 	{ "tpope/vim-dadbod" },
	-- 	{ "kristijanhusak/vim-dadbod-completion", ft = { "sql", "mysql", "plsql" } },
	-- 	{
	-- 		"saghen/blink.cmp",
	-- 		optional = true,
	-- 		opts = {
	-- 			sources = {
	-- 				default = { "dadbod" },
	-- 				providers = {
	-- 					dadbod = { name = "Dadbod", module = "vim_dadbod_completion.blink" },
	-- 				},
	-- 			},
	-- 		},
	-- 	},
	-- },
	-- init = function()
	-- 	local data_path = vim.fn.stdpath("data")
	-- 	vim.g.db_ui_auto_execute_table_helpers = 1
	-- 	vim.g.db_ui_icons = { expanded = "", collapsed = ""}
  -- 	vim.g.db_ui_save_location = data_path .. "/dadbod_u"
  -- 	vim.g.db_ui_tmp_query_location = data_path .. "/dadbod_ui/tm"
  -- 	vim.g.db_ui_use_nvim_notify = false
  -- 	vim.g.db_ui_execute_on_save = false
  -- end,
}
