return {
	-- "kevinhwang91/nvim-ufo",
	-- cmd = "UfoAttach",
	-- keys = {
	-- 	{ "<leader>ou", ":UfoAttach<cr>", desc = "Ufo" },
	-- },
	-- dependencies = {
	-- 	"kevinhwang91/promise-async",
	-- 	{
	-- 		"luukvbaal/statuscol.nvim",
	-- 		config = function()
	-- 			local builtin = require("statuscol.builtin")
	-- 			require("statuscol").setup({
	-- 				relculright = true,
	-- 				segments = {
	-- 					{ text = { builtin.foldfunc }, click = "v:lua.ScFa" },
	-- 					{ text = { "%s" }, click = "v:lua.ScSa" },
	-- 					{ text = { builtin.lnumfunc }, click = "v:lua.ScLa" },
	-- 				},
	-- 			})
	-- 		end,
	-- 	},
	-- },
	-- config = function()
	-- 	vim.o.fillchars = [[eob: ,fold: ,foldopen:,foldsep: ,foldclose:]]
	-- 	vim.o.foldcolumn = "1" -- '0' is not bad
	-- 	vim.o.foldlevel = 99 -- Using ufo provider need a large value, feel free to decrease the value
	-- 	vim.o.foldlevelstart = 99
	--
	-- 	require("ufo").setup({
	-- 		preview = {
	-- 			mappings = {
	-- 				scrollU = "<C-p>",
	-- 				scrollD = "<C-n>",
	-- 				jumpTop = "[",
	-- 				jumpBot = "]",
	-- 			},
	-- 		},
	-- 		provider_selector = function()
	-- 			return { "treesitter", "indent" }
	-- 		end,
	-- 	})
	-- 	vim.keymap.set("n", "zR", require("ufo").openAllFolds)
	-- 	vim.keymap.set("n", "zM", require("ufo").closeAllFolds)
	-- 	vim.keymap.set("n", "zr", require("ufo").openFoldsExceptKinds)
	-- 	vim.keymap.set("n", "zm", require("ufo").closeFoldsWith) -- closeAllFolds == closeFoldsWith(0)
	-- 	vim.keymap.set("n", "K", function()
	-- 		local winid = require("ufo").peekFoldedLinesUnderCursor()
	-- 		if not winid then
	-- 			vim.lsp.buf.hover()
	-- 		end
	-- 	end)
	-- end,
}
