return {
	"utilyre/barbecue.nvim",
	version = "*",
	event = {
		"BufReadPre",
		"BufNewFile",
	},
	dependencies = {
		"SmiteshP/nvim-navic",
	},
	opts = {
		exclude_filetypes = { "netrw", "toggleterm" },
		show_basename = false,
		kinds = {
			File = "",
			Module = "󱒌",
			Namespace = "",
			Package = "",
			Class = "",
			Method = "",
			Property = "",
			Field = "",
			Constructor = "",
			Enum = "ℰ",
			Interface = "",
			--[[ Interface = "", ]]
			Function = "ƒ",
			Variable = "",
			Constant = "",
			String = "",
			Number = "",
			Boolean = "◩",
			Array = "",
			Object = "⦿",
			Key = "🔐",
			Null = "",
			EnumMember = "",
			Struct = "פּ",
			Event = "🗲",
			Operator = "󰆕",
			TypeParameter = "",
		},
	},
}
